name: CI

on: [ push, workflow_dispatch ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        unity-version: [2022.1.4f1, 2021.3.4f1, 2020.3.35f1, 2020.3.22f1, 2019.4.39f1, 2018.4.36f1] # TODO 2017.4.40f1, license no worky
        arch: [x64, x32]
        scripting-backend: [Mono2x, IL2CPP]
        exclude:
          - os: ubuntu-latest
            arch: x32
          - os: ubuntu-latest
            unity-version: 2018.4.36f1
            scripting-backend: IL2CPP
        include:
          - os: ubuntu-latest
            unity-version: 2018.4.36f1 # TODO 2017.4.40f1
            arch: x32
            scripting-backend: Mono2x          

    runs-on: ${{ matrix.os }}

    steps:
      - id: set-vars
        uses: actions/github-script@v5
        with:
          script: |
            const os = "${{ matrix.os }}";
            const arch = "${{ matrix.arch }}";
            const scriptingBackend = "${{ matrix.scripting-backend }}";
            const unityVersion = "${{ matrix.unity-version }}";
            const major = Number.parseInt(unityVersion.split(".")[0]);

            core.setOutput("platform", (os === "ubuntu-latest" ? "Linux" : "Windows") + (arch === "x64" ? "64" : ""));
            core.setOutput("scripting-backend", scriptingBackend === "Mono2x" ? "Mono" : "IL2CPP");
            core.setOutput("module", scriptingBackend === "IL2CPP" ? (os === "ubuntu-latest" ? (major >= 2019 ? "linux-il2cpp" : "") : "windows-il2cpp") : "");
            core.setOutput("extension", os === "windows-latest" ? ".exe" : "");

      - uses: actions/checkout@v2

      - id: setup-unity
        uses: kuler90/setup-unity@v1
        with:
          unity-version: ${{ matrix.unity-version }}
          unity-modules: ${{ steps.set-vars.outputs.module }}

      - name: Activate Unity
        uses: js6pak/activate-unity@master
        with:
          unity-username: ${{ secrets.UNITY_USERNAME }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-authenticator-key: ${{ secrets.UNITY_AUTHENTICATOR_KEY }}

      - name: Build Unity
        uses: js6pak/build-unity@master
        with:
          build-target: Standalone${{ steps.set-vars.outputs.platform }}
          build-scripting-backend: ${{ matrix.scripting-backend }}
          build-path: ./out/TestGame${{ steps.set-vars.outputs.extension }}

      - uses: actions/upload-artifact@v2
        with:
          name: TestGame ${{ steps.set-vars.outputs.scripting-backend }} ${{ steps.set-vars.outputs.platform }} ${{ matrix.unity-version }}
          path: out
          
      - shell: bash
        run: |
          cd out
          7z a -tzip "${{ steps.set-vars.outputs.scripting-backend }} ${{ steps.set-vars.outputs.platform }} ${{ matrix.unity-version }}.zip" .

      - uses: actions/upload-artifact@v2
        with:
          name: TestGame
          path: out/*.zip

  create_release:
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Collect files
        id: collect-info
        run: |
          mkdir release
          cd artifacts
          for i in */; do (cd "${i%/}" && zip -0 -r "../../release/${i%/}.zip" *) & done; wait
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          title: "Build ${{ github.run_number }}"
          files: |
            release/*.zip
