name: CI

on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest]    
        os: [ubuntu-latest]    
        unity-version: [2020.3.25f1, 2019.4.34f1, 2018.4.36f1] # TODO 2017.4.40f1
        arch: [x64, x32]
        exclude:
          - os: ubuntu-latest
            arch: x32

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - id: setup-unity
        uses: kuler90/setup-unity@v1
        with:
          unity-version: ${{ matrix.unity-version }}

      - name: Activate Unity
        uses: js6pak/activate-unity@master
        with:
          unity-username: ${{ secrets.UNITY_USERNAME }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-authenticator-key: ${{ secrets.UNITY_AUTHENTICATOR_KEY }}

      - name: Build Unity
        uses: js6pak/build-unity@master
        with:
          build-target: StandaloneLinux64
          build-path: ./out/TestGame.exe
    
      - uses: actions/upload-artifact@v2
        with:
          path: out
